name:                FreeType-convert
version:             0.1.0.0
github:              "Krantz-XRF/FreeType"
license:             BSD3
author:              "Krantz-XRF"
maintainer:          "Krantz.XRF@outlook.com"
copyright:           "(c) Krantz 2019"

extra-source-files:
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Krantz-XRF/FreeType#readme>

dependencies:
- base >= 4.7 && < 5
- Rasterific
- JuicyPixels

executables:
  FreeType-convert:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - FreeType
    - FreeType-Rasterific
